[package]
name = "byocvpn_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
byocvpn_core = { path = "../core" }
byocvpn_aws = { path = "../infra/aws" }
tokio = { workspace = true }
clap = { version = "4.5.49", features = ["derive"] }
